
[package]
name = "conn_pool"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
crossbeam-queue = "0.3.8"
dashmap = "5.5.0"
tokio = { version = "1", default-features = false, features = ["time"]}
tokio-stream = { version = "0.1" }
futures = "0.3.28"
tracing = "0.1.37"
