[package]
name = "version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
vergen = { version = "8.2.4", features =  ["build", "git", "gitcl", "rustc"] }
